dist: xenial
services:
- postgresql
addons:
  chrome: stable
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
before_install:
- sudo apt-get -y install chromium-chromedriver
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install selenium
script:
- cd decide
- cp travis_local_settings.py local_settings.py
deploy:
  provider: heroku
  app: decide-full-guadalfeo-cabina
  strategy: git
  api_key:
    secure: M+NvuCG2Avasqnc+RoMG/ztriChpJCyT3psXYgyDyoG35QtAzca5KNZqr4A3pU7/GtO8YtqOS2JAvSSx8r3glO0n2NMf08l/pxNZikC5yALkNOQzus/cLvE8UNv7SK/1W6Mz5DB95idEJO+9XwOtftYhwb/MpsE2sLIagvLgpU4BYpEMgwIav2jvh1y72W9YyVFAPWZwbzc7wf3lwWq95yxykloctIlG/XUkNLwIV7krD3jcstVHr11OEcbxqMDdauxWlazzALZCh2IEdRcteTfdbItQ09LRkkmTqBUmqyOxJdDnkfmXpU8CEbbHeaJHxwFod4McXqIucg08qWsEjDyT2YdJd1Jz8jY8QzynBSBZ3Z6iqKrb4dl9/SPxbW/cvXy9ldqV8FXYpEUf3iD2jOmf7aiiTzB88d2RZhmcxyUF3fLnIyDkA1wV0X7m77qjsU7proQCVWC6hypyXacTNyeu06U8MYCwrNLpsHxSP6pZfqL7NaaeIwqrbDxK9xaZQ7nxziAHWK+dPo5dXqI200m5SP5PcT8aaScnP1GE9N6U+w6vJdCwwW5IT2+GhWpwkGZhuhvijvK26YbwNnHUFO5qvpY0OdUSYCRDU03RzKB7jznusMfxs/4c/e3kDOiOQUa25tH4h4QQo83NhI07sUdanWFdfwBdopl9Ik/8wKs=
  on:
    branch: main
