# Generated by Django 2.0 on 2021-01-07 19:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'default': 'default'}),
            preserve_default=False,
        ),
    ]
